name: sahayak_mobile
description: Sahayak mobile app (Senior Citizen & Volunteer flows)
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.6.0
  livekit_client: ^2.13.0
  permission_handler: ^13.0.2
  flutter_secure_storage: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
